/**
 * O'zbekiston viloyatlari va tumanlari
 * Markazlashtirilgan ma'lumot — barcha sahifalarda shu import ishlatiladi
 */

export const regionDistricts: Record<string, string[]> = {
  "Toshkent shahri": [
    "Bektemir",
    "Chilonzor",
    "Mirobod",
    "Mirzo Ulug'bek",
    "Olmazor",
    "Sergeli",
    "Shayxontohur",
    "Uchtepa",
    "Yakkasaroy",
    "Yashnobod",
    "Yunusobod",
  ],
  "Toshkent viloyati": [
    "Bekobod",
    "Bo'ka",
    "Bo'stonliq",
    "Chinoz",
    "Ohangaron",
    "Oqqo'rg'on",
    "Parkent",
    "Piskent",
    "Quyi Chirchiq",
    "Yangiyo'l",
    "Yuqori Chirchiq",
    "Zangiota",
  ],
  Andijon: [
    "Andijon",
    "Asaka",
    "Baliqchi",
    "Bo'z",
    "Buloqboshi",
    "Izboskan",
    "Jalaquduq",
    "Marhamat",
    "Oltinko'l",
    "Paxtaobod",
    "Qo'rg'ontepa",
    "Shahrixon",
    "Ulug'nor",
    "Xo'jaobod",
  ],
  "Farg'ona": [
    "Bag'dod",
    "Beshariq",
    "Buvayda",
    "Dang'ara",
    "Farg'ona",
    "Furqat",
    "Oltiariq",
    "Qo'qon",
    "Quva",
    "Quvasoy",
    "Rishton",
    "So'x",
    "Toshloq",
    "Uchko'prik",
    "Yozyovon",
  ],
  Namangan: [
    "Chortoq",
    "Chust",
    "Kosonsoy",
    "Mingbuloq",
    "Namangan",
    "Norin",
    "Pop",
    "To'raqo'rg'on",
    "Uchqo'rg'on",
    "Uychi",
    "Yangiqo'rg'on",
  ],
  Samarqand: [
    "Bulung'ur",
    "Ishtixon",
    "Jomboy",
    "Kattaqo'rg'on",
    "Narpay",
    "Nurobod",
    "Oqdaryo",
    "Pastdarg'om",
    "Paxtachi",
    "Payariq",
    "Qo'shrabot",
    "Samarqand",
    "Tayloq",
    "Urgut",
  ],
  Qashqadaryo: [
    "Chiroqchi",
    "Dehqonobod",
    "G'uzor",
    "Kasbi",
    "Kitob",
    "Koson",
    "Mirishkor",
    "Muborak",
    "Nishon",
    "Qamashi",
    "Qarshi",
    "Shahrisabz",
    "Yakkabog'",
  ],
  Surxondaryo: [
    "Angor",
    "Bandixon",
    "Boysun",
    "Denov",
    "Jarqo'rg'on",
    "Muzrabot",
    "Oltinsoy",
    "Qiziriq",
    "Qumqo'rg'on",
    "Sariosiyo",
    "Sherobod",
    "Sho'rchi",
    "Termiz",
    "Uzun",
  ],
  Buxoro: [
    "Buxoro",
    "G'ijduvon",
    "Jondor",
    "Kogon",
    "Olot",
    "Peshku",
    "Qorako'l",
    "Qorovulbozor",
    "Romitan",
    "Shofirkon",
    "Vobkent",
  ],
  Navoiy: [
    "Karmana",
    "Konimex",
    "Navbahor",
    "Navoiy",
    "Nurota",
    "Qiziltepa",
    "Tomdi",
    "Uchquduq",
    "Xatirchi",
  ],
  Jizzax: [
    "Arnasoy",
    "Baxmal",
    "Do'stlik",
    "Forish",
    "G'allaorol",
    "Jizzax",
    "Mirzacho'l",
    "Paxtakor",
    "Yangiobod",
    "Zafarobod",
    "Zarbdor",
    "Zomin",
  ],
  Sirdaryo: [
    "Boyovut",
    "Guliston",
    "Mirzaobod",
    "Oqoltin",
    "Sardoba",
    "Sayxunobod",
    "Sirdaryo",
    "Xovos",
    "Yangiyer",
    "Shirin",
  ],
  Xorazm: [
    "Bog'ot",
    "Gurlan",
    "Hazorasp",
    "Khiva",
    "Qo'shko'pir",
    "Shovot",
    "Urganch",
    "Yangiariq",
    "Yangibozor",
  ],
  "Qoraqalpog'iston": [
    "Amudaryo",
    "Beruniy",
    "Bo'zatov",
    "Chimboy",
    "Ellikqal'a",
    "Kegeyli",
    "Mo'ynoq",
    "Nukus",
    "Qanliko'l",
    "Qo'ng'irot",
    "Qorao'zak",
    "Shumanay",
    "Taxtako'pir",
    "To'rtko'l",
    "Xo'jayli",
  ],
};

/** Viloyatlar ro'yxati */
export const regions = Object.keys(regionDistricts);

/** Tanlangan viloyat bo'yicha tumanlar */
export function getDistricts(region: string): string[] {
  return regionDistricts[region] || [];
}
